name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - toolchain: stable
          - toolchain: 1.75.0 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
            toolchain: ${{ matrix.rust.toolchain }}
            override: true
      - name: Build + Test
        run: |
          cargo build --no-default-features
          cargo test --no-fail-fast --all-features

  fmt:
    name: Rust fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
            toolchain: stable
            components: rustfmt
      - name: Rust fmt
        run: cargo fmt --all -- --check

  clippy:
    name: Rust clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
            toolchain: 1.84.0
            components: clippy
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
