name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - toolchain: stable
          - toolchain: 1.63.0
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
            toolchain: ${{ matrix.rust.toolchain }}
            override: true
      - name: Build + Test
        run: |
          cargo build --no-default-features
          cargo test --no-fail-fast --all-features

  fmt-clippy:
    name: Rust fmt & clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
            toolchain: stable
            components: clippy, rustfmt
            override: true
      - name: Rust fmt
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
